### ISSUE TITLE
Running submit caused IndexError (Ghostbin !submit support broken)

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector-discord-bot#106]
msg ID: https://discord.com/channels/817916789668708384/837779037900374059/927348017080696902

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/code/cogs/msg_commands/BotSubmissionsCommands.py", line 55, in submit
    List = sql.get_ghostbin_paste_names(paste_soup)
  File "/code/utils/sql.py", line 142, in get_ghostbin_paste_names
    lines = paste_soup.select('body > div.container > textarea').pop().decode_contents()
IndexError: pop from empty list

Could be an issue with using ghostbin vs pastebin

**Comment by ThorntonMatthewD** [comment]
Ghostbin changed their layout again :')

**Comment by Ferrariic** [comment]
nOOOOO
