### ISSUE TITLE
AttributeError: 'int' object has no attribute 'status'

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector-discord-bot#109]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/code/cogs/msg_commands/PlayerStatsCommands.py", line 264, in rankup
    linkedAccounts = await discord_processing.get_linked_accounts(self.bot.session, member.id, token)
  File "/code/utils/discord_processing.py", line 63, in get_linked_accounts
    raise HTTPException(r.status, "Could not grab data.")
  File "/usr/local/lib/python3.9/site-packages/discord/errors.py", line 90, in __init__
    self.status = response.status
AttributeError: 'int' object has no attribute 'status'

**Comment by ThorntonMatthewD** [comment]
I did not implement great HTTP error handling. This is almost certainly the API presenting a 500 error. I'll try to handle it more elegantly (however, the command will still not work in the end).

**Comment by Ferrariic** [comment]
Oh yeah that's fine if it doesn't work - we should just get a diff response for the code :D
