### ISSUE TITLE
Add fix for !kc and !link commands, and probably every other cmd that talks to api

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector-discord-bot#155]

**Comment by Ferrariic** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/code/cogs/msg_commands/RSNLinkCommands.py", line 28, in link
    previous_attempts = await discord_processing.get_verification_attempts(self.bot.session, player_name=joined_name, token=token)
  File "/code/utils/discord_processing.py", line 31, in get_verification_attempts
    raise HTTPException(r.status, "Could not grab data.")
  File "/usr/local/lib/python3.9/site-packages/discord/errors.py", line 90, in __init__
    self.status = response.status
AttributeError: 'int' object has no attribute 'status'
```
